<?php

return array(
    'results'=>'Results',
    'thankyou'=>'
Thank you for completing IDC’s Converge Infrastructure - Maturity Benchmark sponsored by Dell and Intel. The economic benefits of being future ready are clear — increased future readiness corresponds to better business outcomes.

Organizations don’t have to be at the top of the future-readiness scale to enjoy benefits; data from a number of IDC Converged Infrastructure and Cloud studies have shown that organizations can obtain benefits by moving to the next stage of future readiness regardless of where you start. Organizations that improve their "future readiness" consistently improve their time to market with new products and services, increase business agility, employee productivity and even improved innovation.

The more that an IT organization is future ready, the more that they enjoy significant business advantages over their competition, including:
',
    'aims'=>'The quiz was designed to help establish your organization\'s readiness to cope with the evolving demands that businesses place on IT infrastructure, both today and into the future.',
    'bullets'=>'
<ul style="color: #2A96DE; line-height: 1.5; list-style-type:img|png|2|2|'.K_PATH_IMAGES.'/bullet.png">
    <li>Faster time to market for new products and services, which allow them to better capture competitive advantages</li>
    <li>Superior business agility and flexibility, enabling them to anticipate and respond quickly to changes in the market, mitigate threats, and capture opportunities</li>
    <li>Increased employee productivity, allowing them to optimize business processes and reduce costs while increasing output</li>
    <li>Enhanced customer experience to deliver more reliable, intuitive and better performing services to employees, partners, and customers</li>
    <li>Innovation, which enables them to move resources and operations into new business areas</li>
    <li>More efficient IT operations, helping reduce costs while creating a more scalable infrastructure</li>
    <li>Enablement of mobile operations to deliver a full range of business applications</li>
<ul>',
    'looked'=>'We looked at the following key areas:',
    'itbusiness'=>'IT and the Business',
    'itservicedelivery'=>'IT Service Delivery',
    'itinfrastructure'=>'IT Infrastructure Technology',

    'based'=>'Based on your responses, we would classify your overall IT Infrastructure Future Readiness as:',
    'currentintro'=>'Evolutionary approach to IT infrastructure and individualistic-driven IT transformation. IT and the business operate on a request/requirements basis.',
    'future-awareintro'=>'Evolutionary approach to IT service delivery and Team-driven IT transformation. IT has alignment with business across specific functions.',
    'future-focusedintro'=>'Revolutionary approach to IT service delivery and IT-organization driven IT transformation. IT and the business are aligned across a number of meaningful activities.',
    'future-creatorintro'=>'Revolutionary approach to digital business with business driven IT transformation. IT/LOBs are aligned across most meaningful activities.',

    'currentaware'=>'You have been rated #STATUS#, and have some work to do to improve the future readiness of your IT infrastructure. But do not be disheartened. Future readiness is an ongoing journey, and you can see significant improvements in business outcomes from increasing your future readiness regardless of your starting point. You can drive business results by choosing to focus on improving the specific aspects of IT Future Readiness landscape that we\'ve highlighted for you:',
    'focusedcreator'=>'You have been rated #STATUS#, and are doing pretty well on the future readiness of your IT infrastructure. But even for those doing well, future readiness is an ongoing journey, and you can still see improvements in business outcomes from increasing your future readiness. As technologies, business practices, and market demands change over time, the concept of future readiness will also evolve. To maintain future readiness, organizations can’t become complacent –think of future readiness as an ongoing journey and stay nimble, adaptable, and innovative to maintain their competitive edge. You can drive business results by choosing to focus on improving the specific aspects of IT Future Readiness landscape that we\'ve highlighted for you:',

    'basedimprove'=>'Based on your responses you can look to improve your overall score by focusing on improving your:',
    'overall'=>'Overall Readiness',
    'yourscore'=>'Your Score',
    'baselinescore'=>'Baseline Score',
    'section'=>'Section Results',
    'getahead'=>'How to get ahead?',
    'itbusinesssummary'=>'According to your responses in this section, your organization\'s relationship between IT and the Business is',
    'itbusiness1'=>'Top recommendation: Good IT starts with good business, and getting this right. In today\'s digital world IT should no longer be regarded as a cost centre, but forms a crucial part of competitive strategy. IT needs to be capable of translating business requirements into technology and services. It is not good enough to buy the latest gear, but systems have to be sufficiently integrated and business processes and structures aligned accordingly. Organisations that apply innovative approaches to their infrastructure and manage these with a business mindset tend to stay ahead of the curve and can focus on creating business value instead of spending valuable time, money and energy firefighting.',
    'itbusiness2'=>'Top recommendation: The most future ready IT organizations really help their companies to adapt to changing market conditions and actively enable them to chase new revenue opportunities as they emerge. Improving relations with business leaders to understand the value that a future ready IT organization can bring will help to support and fund the improvements you need to implement in order to keep up with your peers. Your position in the organisation could gain importance if you manage to apply IT as a revenue driver. However, if you fail to show progress then your role could become more administrative, and pressure will mount due to increasing demands by end-users and the growth of shadow IT.',
    'itbusiness3'=>'Top recommendation: Investment is crucial to developing a capable and agile IT organization. You\'re currently struggling to attract funding for running IT or developing new initiatives, with the result that you will have challenges transforming IT. You should consider a new approach to IT strategy looking at the value you can bring to the business by transforming IT. This will look to identify the savings from efficiency improvement and then investing this to build a modern platform approach for offering new services to the business.',
    'itbusiness4'=>'Top recommendation: You are struggling to deal with change, which means your company will find it difficult to react to shifting conditions in the marketplace. Look to ways to make change more predictable and quicker to action by examining gaps and weaknesses in your tools and processes. Your systems and operational processes need to be reassessed and possibly upgraded to ensure that they are meeting key business objectives and are ready for the digital age. Your department may also need to improve its skill set by hiring relevant specialists or providing sufficient training. Efficient collaboration within your team and with business decision makers is crucial for dealing with the challenges of business and IT transformation.',
    'itbusiness5'=>'Top recommendation: With many projects proceeding without the required level of input from the IT department, the business is not engaging well with IT. One of your main priorities should be to build and improve the relations between IT and company or line of business management, while also ensuring that management is aware of the capabilities and successes of the IT department. This may require rethinking from both sides to achieve that IT is seen as an internal service provider that adds crucial business value rather than a back office as a necessary evil.',
    'itbusiness6'=>'Top recommendation: Self-awareness and identify gaps and weaknesses are key elements when it comes to understanding where to focus on improving IT. At a minimum, you should be looking to implement a formal review of the IT department\'s delivery and capabilities. Ideally, you should bring in experienced experts who can give a balanced opinion on what is required based on industry accepted best practice. Following your competitors\' business performance and changes in their IT strategy could help you better understand the correlation between these factors in order to move up a maturity level and assess your strengths and weaknesses.',
    'itservicedeliverysummary'=>'According to your responses in this section, your organization\'s IT Service Delivery capability is',
    'itservicedelivery1'=>'Top recommendation: Effective and aligned IT organizations are a foundation for modern digital businesses. An effective IT organization contains the right people with the right skills to implement and maximize the benefits of those technologies. To move up the future-ready spectrum, the IT organization must increasingly work strategically with every LOB. Organizing to be fully responsive to LOB requirements is the critical first step to move along the future-ready enterprise journey. The organizations that are best at IT Service Delivery measure their service performance against other firms. IDC research shows that Future Creators are up to three times more likely to track and competitively benchmark IT service levels on key metrics. This leads to more continuous improvements, and ultimately leads to better partnerships with various Lines of Business.',
    'itservicedelivery2'=>'Top recommendation: Building out IT service delivery capabilities is crucial for getting more value out of your operations and increase efficiency. By providing self-service provisioning and management tools, as well as a clearly defined service catalogue, services can be applied in a more coordinated and integrated way, increasing predictability and ease of use. Automating tasks can free up developers\' and admins\' times so that they can focus on value-adding innovation. User satisfaction and application performance monitoring can provide valuable insight for understanding your pain points and help you avoid costly downtimes.',
    'itservicedelivery3'=>'Top recommendation: Consider implementing shared IT infrastructure wherever possible to avoid any unnecessary overlaps and inefficiencies in resource usage. Datacentre floor space and the operation and maintenance of hardware is expensive, especially their power consumption. It is recommended that you make every effort to consolidate your infrastructure in a shared and integrated manner to remain competitive. Consider using a converged infrastructure solution that is designed to be pre-integrated and to work together out the box to speed up your transformation.',
    'itservicedelivery4'=>'Top recommendation: Investment in end-to-end IT service monitoring and management tools should no longer be considered a nice-to-have, but is essential for keeping your systems up and running and avoid costly downtimes or security issues. They also help with proactive service quality management and keep customers or employees happy and reduce the cost of support. They can also provide useful analytics that can help you achieve competitive advantage by better understanding your users\' needs. Look at whether your infrastructure supplier has a supported and integrated service management solution as part of their offering to avoid having to integrate and adapt expensive third party software.',
    'itservicedelivery5'=>'Top recommendation: Your management tools are quite basic and fragmented, and are not ready for managing the increasingly converging server, storage and networking environments of the future. Consider implementing an end-to-end management suite that gives you holistic control and insight into your infrastructure so that you can optimize your resource usage and operational processes.',
    'itservicedelivery6'=>'Top recommendation: IT management needs to be automated in order to increase efficiency, agility and consistency, and to minimize the risk of human error and free up admins\' and developers\' time to focus on value-adding activities. In the digital age, automation needs to be applied across the board to remain competitive and be able to sufficiently integrate various processes and systems. Don\'t forget that when you embark on an automation effort to identify potential savings in advance to ring-fence these for re-investment into it to improve service delivery.',
    'itservicedelivery7'=>'Top recommendation: It is no longer good enough to run your IT operations in separate teams for server, storage and networking that are acting a siloes. All three areas need to be fully integrated for achieving competitive advantage and avoid internal process bottlenecks. It is a truly challenging task and may lead to reshuffling staff responsibilities, but cannot be avoided if you want to get ready for the future.',
    'itinfrastructuresummary'=>'According to your responses in this section, your organization\'s approach to IT Infrastructure Technology is',
    'itinfrastructure1'=>'Top recommendation: Converged infrastructure, meaning using integrated bundles of hardware and software components grouped into a single optimized package, allows organizations to better utilize their existing IT assets. It provides an agile, scalable foundation organizations can rely on as they change business processes and launch new services. Speed and agility are very important and automating the management of compute, network and storage resources into a single management pane is critical to improving availability and reducing costs via increased asset utilization across each datacenter resource. 
How are Future Creators getting more value from their converged IT infrastructure? It starts with accurately measuring utilization rates for compute, storage and network. They are using more sophisticated tools and measuring infrastructure utilization more regularly compared to other organizations. They are also making the organizational changes necessary to get the most benefits from their converged infrastructure. They are actively looking to differentiate their business using applications, data and infrastructure while deferring more responsibility for IT automation and configuration management to their development teams.',
    'itinfrastructure2'=>'Top recommendation: Infrastructure virtualization and cloud solutions can provide some relief for organisations who struggle getting value and performance out of their legacy hardware. However, if you want to be truly competitive you\'ll need to go a step further by taking advantage of integrated bundles of hardware and software components. Converged infrastructure can group components into a single optimized package, which allows you to realise much faster time to value as well as better utilization of your existing IT assets. It provides an agile, scalable foundation you can rely on as business processes change and new services are launched.',
    'itinfrastructure3'=>'Top recommendation: Third party managed services and hosted solutions can help you by offering best practice or pre-build environments, allowing you to concentrate on your core business while your IT is taken care of by selected companies who specialize in this field. While it is not always the best option to outsource your IT, it is generally recommended to evaluate the various offerings in the market and make use of them where appropriate to avoid falling behind in competitiveness, efficiency and scalability. It is key to integrate these services tightly with your on-premises environment and manage these supplier relationships with a clear vision that unifies business and technical aspects.',
    'itinfrastructure4'=>'Top recommendation: Public Cloud Services can provide a more agile, capable and effective use of IT infrastructure and resources, enabling more to be delivered with the same IT budget. Public Cloud can improve business agility, leading to faster response to competitors which can allow you to become a leader in industry transformation. New products and services can be tested and launched more quickly and with less risk by scaling cloud resources up and down instantly when needed. The most advanced organizations have hybrid strategies in place, that allow for seamless workload movement across On-Premises and Public Cloud resources.',
    'itinfrastructure5'=>'Top recommendation: In order to achieve competitive advantage in this increasingly digital economy, you should look to become an innovator and try out new technologies before your competitors do. Do not wait until all your peers have approved of a new hardware or software, but actively look out for innovative approaches that are relevant for your business. These often involve the integration of servers, storage, networking and management software as converged systems. Seek advice from your local system integrator who can explain the different approaches and assess the cost savings, flexibility and innovative credentials that you could be gaining from a new implementation. Make sure that you align your internal operations teams and change management accordingly so that you\ll be able to make the most of adopting new technologies.',
    'itinfrastructure6'=>'Top recommendation: You need to have a clear plan in place for buying your server, storage and networking infrastructure. It is not sufficient to simply consolidate your teams\' requirements, but your machines need to be purchased strategically as a holistic solution to avoid fragmentation as well as management and support headaches. This doesn\'t mean that you need to lock yourself in by buying only from one vendor. However, most organizations find that converged systems provide competitive advantage and faster time to value over separate, less integrated and manageable infrastructure elements.',
    'conclusion'=>'Conclusion',
    'conclusionsummary'=>'
Future-ready IT is a key enabler of today’s enterprises, and the organizations with the highest levels of future readiness not only quickly adapt to disruptions, but also drive innovation. Achieving greater levels of future readiness does not come without risks and pitfalls to avoid. These include:
<ul style="color: #2A96DE; line-height: 1.5; list-style-type:img|png|2|2|'.K_PATH_IMAGES.'/bullet.png">
    <li>Going in without a plan. Companies need to be deliberate and thoughtful about their approach to becoming more future-ready. Becoming future-ready requires more than simply throwing new technology into the IT organization. It requires having in place the organization, skills, and practices are in place to take advantage of that technology, and that the technology supports critical business initiatives.</li>
    <li>Proprietary lock-in. Key to being future-ready is the flexibility to adapt to unforeseen circumstance. Locking into a proprietary offering or framework limits the organization’s flexibility and increases the risk of choosing a technology dead-end.</li>
    <li>Big bets. Organizations should take a step-wise approach to improving their future readiness, building incrementally on the IT infrastructure and practices they have in place. With so much of the business dependent on IT, upgrading the infrastructure amounts to performing an organizational heart transplant. Wholesale change-outs, while promising the ability to leapfrog</li>
</ul>
Fortunately, organizations lower on the future-readiness scale don’t need to achieve the highest levels of future readiness to begin seeing improvements. Future readiness is a journey, and moving up a single level regardless of your starting point improves business outcomes. Companies can also choose to focus on whichever technology or practice area most appropriate to their business needs and still see improvements. However, two elements are fundamental for success across all levels: a strategic approach that drives business decisions vs. a short-term focus on cost reduction, and an IT organization that can work closely with LOB to address the needs of the organization.',
    'sponsored'=>'Sponsored by HP'
);