<?php

return array(
    'results'=>'RÉSULTATS',
    'thankyou'=>"
Nous vous remercions d'avoir répondu à l'évaluation IDC « Votre infrastructure est-elle évolutive ? » parrainée par Dell et Intel. Les avantages économiques de l'évolutivité sont évidents : qui dit évolutivité accrue dit meilleurs résultats commerciaux. 
Les entreprises n'ont pas à afficher une évolutivité optimale pour en récolter les fruits ; selon plusieurs études d'IDC sur l'informatique et le cloud computing, les entreprises ont tout à gagner à franchir un palier d'évolutivité, quel soit leur point de départ. Les entreprises qui améliorent leur évolutivité améliorent constamment leur temps de mise sur le marché de nouveaux produits et services, optimisent leur flexibilité, la productivité de leurs employés et même leurs innovations.

Plus une structure informatique est évolutive, plus elle peut profiter d'avantages commerciaux significatifs par rapport à la concurrence, notamment :
",
    'aims'=>"Le questionnaire a été conçu pour vous aider à déterminer si votre entreprise est prête à faire face à l'évolution des exigences des entreprises en termes d'infrastructure informatique, aujourd'hui et à l'avenir.",
    'bullets'=>'
<ul style="color: #2A96DE; line-height: 1.5; list-style-type:img|png|2|2|'.K_PATH_IMAGES.'/bullet.png">
    <li>Une commercialisation plus rapide de nouveaux produits et services, qui lui permettent de mieux saisir les avantages concurrentiels</li>
    <li>Une flexibilité commerciale supérieure, permettant d\'anticiper et de prendre en compte rapidement les changements du marché, d\'atténuer les menaces et de saisir les opportunités</li>
    <li>Une productivité des employés accrue, permettant à l\'entreprise d\'optimiser les processus métier et de réduire les coûts tout en augmentant le rendement</li>
    <li>Une expérience client optimisée pour fournir des services plus fiables, plus intuitifs et plus efficaces aux employés, partenaires et clients</li>
    <li>L\'innovation, qui permet à l\'entreprise de transférer les ressources et activités vers de nouveaux secteurs</li>
    <li>Une exploitation informatique plus efficace, pour réduire les coûts tout en créant une infrastructure plus évolutive</li>
    <li>Une activation des opérations mobiles pour offrir une gamme complète d'applications d'entreprise</li>
<ul>',
    'looked'=>'Nous nous sommes penchés sur les domaines clés suivants :',
    'itbusiness'=>'Informatique et entreprise',
    'itservicedelivery'=>'Prestation de services informatiques',
    'itinfrastructure'=>'Technologie d\'infrastructure informatique',

    'based'=>'Selon vos réponses, l\'évolutivité générale de votre infrastructure informatique figure dans la catégorie suivante :',
    'currentintro'=>'approche évolutive de l\'infrastructure informatique et une transformation informatique en fonction des besoins spécifiques. L\'informatique et l\'entreprise fonctionnent selon les requêtes et les besoins.',
    'future-awareintro'=>'approche évolutive de la prestation de services informatiques, axée sur une transformation basée sur le travail d\'équipe. L\'informatique s\'aligne sur l\'entreprise via des fonctions spécifiques.',
    'future-focusedintro'=>'approche révolutionnaire des services informatiques et une transformation informatique basée sur l\'alignement informatique/entreprise. L\'informatique et l\'entreprise sont alignées dans un certain nombre d\'activités utiles.',
    'future-creatorintro'=>'approche révolutionnaire du marché numérique et une transformation informatique basée sur l\'entreprise. L\'informatique et les secteurs d\'activité sont alignés dans la plupart des activités pertinentes.',

    'currentaware'=>'Vous figurez dans la catégorie #STATUS#. Il vous reste du chemin à parcourir pour rendre votre infrastructure informatique plus évolutive. Mais ne soyez pas découragé. Il s\'agit d\'un cheminement continu, et vous pourrez améliorer sensiblement vos résultats commerciaux en imisant votre évolutivité, quel que soit votre point de départ. Vous pouvez améliorer vos résultats commerciaux en améliorant certains aspects spécifiques de l\'évolutivité de votre structure informatique. Nous les avons soulignés:',
    'focusedcreator'=>'Vous figurez dans la catégorie #STATUS#. Vous vous en tirez assez bien concernant l\'évolutivité de votre infrastructure informatique. Mais même pour les entreprises qui s\'en sortent bien, l\'évolutivité est un cheminement continu. Continuez à optimiser votre évolutivité pour améliorer vos résultats commerciaux. À mesure de l\'évolution des technologies, des pratiques commerciales et des exigences du marché, le concept d\'évolutivité change lui aussi. Les entreprises ne peuvent se laisser aller à la complaisance si elles veulent préserver leur évolutivité. Envisagez l\'évolutivité comme un cheminement continu et restez flexible, adaptable et novateur pour maintenir votre avantage concurrentiel. Vous pouvez améliorer vos résultats commerciaux en améliorant certains aspects spécifiques de l\'évolutivité de votre structure informatique. Nous les avons soulignés :',

    'basedimprove'=>'Based on your responses you can look to improve your overall score by focusing on improving your:',
    'overall'=>'Overall Readiness',
    'yourscore'=>'VOTRE SCORE',
    'baselinescore'=>'SCORE DE RÉFÉRENCE',
    'section'=>'RÉSULTATS PAR CATÉGORIE',
    'getahead'=>'Comment progresser ?',
    'itbusinesssummary'=>'Selon vos réponses à cette catégorie, la relation informatique/marché de votre entreprise est',
    'itbusiness1'=>"Recommandation principale : qui dit informatique efficace, dit entreprise efficace. Dans le monde numérique d'aujourd'hui, l'informatique ne doit plus être considérée comme un centre de coût, mais comme une pièce maîtresse de la stratégie concurrentielle. L'informatique doit être capable de traduire les exigences opérationnelles en technologie et services. Il ne suffit pas d'acheter les derniers équipements, mais les systèmes doivent être suffisamment intégrés et les processus métier et les structures doivent être alignées en conséquence. Les entreprises appliquant des approches innovatrices à leur infrastructure et gérant ces approches dans une optique commerciale ont tendance à rester dans le wagon de tête et peuvent se concentrer sur la création de valeur commerciale plutôt que de consacrer un temps précieux à résoudre des problèmes dans l'urgence.",
    'itbusiness2'=>"Recommandation principale : les structures informatiques les plus évolutives aident vraiment les entreprises à s'adapter aux conditions changeantes du marché et à leur permettre activement de poursuivre les nouvelles opportunités de chiffre d'affaires qui se présentent. Aider les dirigeants d'entreprises à comprendre la valeur que peut apporter une structure informatique évolutive permettra d'appuyer et financer les améliorations à mettre en œuvre pour soutenir la cadence dictée par la concurrence. Votre position dans l'entreprise pourrait gagner en importance si vous parvenez à utiliser l'informatique comme un vecteur de chiffre d'affaires. Toutefois, si vous ne pouvez pas afficher de progrès, votre rôle pourrait devenir plus administratif, et la pression ira crescendo en raison des exigences grandissantes des utilisateurs finaux et de l'essor du «l’informatique parallèle ».",
    'itbusiness3'=>"Recommandation principale : l'investissement est crucial pour le développement d'une structure informatique flexible et capable. Vous peinez actuellement à attirer des fonds destinés à l'exploitation informatique et au développement de nouvelles initiatives. Résultat : il vous sera difficile de transformer votre structure informatique. Vous devriez envisager une nouvelle approche de stratégie informatique, en vous penchant sur la valeur que vous pouvez apporter à l'entreprise grâce à sa transformation. Cela permettra d'identifier les économies réalisées grâce à l'amélioration du rendement, et puis d'investir ces fonds dans une plate-forme moderne pour fournir de nouveaux services à l'entreprise.",
    'itbusiness4'=>"Recommandation principale : vous peinez à composer avec le changement, ce qui signifie que votre entreprise réagira difficilement aux changements de conditions du marché. Recherchez des moyens de rendre le changement plus prévisible et de prendre plus rapidement les mesures qui s'imposent en examinant les lacunes et les faiblesses de vos outils et vos processus. Vos systèmes et processus opérationnels doivent être réévalués et éventuellement mis à niveau pour qu'ils respectent les objectifs commerciaux clés et soient prêts pour l'ère numérique. Votre service peut également avoir besoin d'améliorer ses compétences en embauchant les spécialistes adéquats ou en assurant une formation suffisante. Une collaboration efficace au sein de votre équipe et avec les décideurs commerciaux est essentielle pour relever les défis relatifs concernant votre entreprise et sa transformation informatique.",
    'itbusiness5'=>"Recommandation principale : compte tenu des nombreux projets lancés sans l'apport requis de la part du service informatique, les interactions entreprise/informatique gagnent à être améliorées. L'une de vos principales priorités devrait être de renforcer et d'améliorer la relation entre l'informatique et la société ou le secteur d'activité, tout en s'assurant que la direction est au courant des capacités et des réussites du service informatique. Cela peut nécessiter une refonte des deux côtés afin que l'informatique soit bien considérée comme un fournisseur de services interne qui ajoute de la valeur essentielle, au lieu d'un système back-office vu comme un mal nécessaire.",
    'itbusiness6'=>"Recommandation principale : la conscience de soi et l'identification des lacunes et faiblesses sont déterminantes pour savoir quels sont les domaines d'amélioration prioritaires de l'informatique. Au minimum, vous devriez envisager une évaluation formelle des prestations et capacités du service informatique. Idéalement, vous devriez vous adjoindre les services d'experts chevronnés pouvant offrir un avis objectif sur les mesures à prendre, en fonction des pratiques d'excellence du secteur. Suivre les résultats commerciaux de vos concurrents et leurs changements de stratégie informatique pourrait vous aider à mieux comprendre la corrélation entre ces facteurs. Vous serez ainsi en mesure de franchir un nouveau palier de maturité et d'évaluer vos forces et vos faiblesses.",
    'itservicedeliverysummary'=>'Selon vos réponses à cette catégorie, la prestation de services informatiques de votre entreprise est',
    'itservicedelivery1'=>"Recommandation principale : les structures informatiques efficaces et alignées constituent un fondement pour les entreprises numériques modernes. Une structure informatique efficace dispose des employés adaptés aux compétences adaptées pour appliquer et optimiser les avantages de ces technologies. Pour franchir un nouveau palier d'évolutivité, la structure informatique doit assurer une collaboration toujours plus stratégique avec chaque secteur d'activité. Première étape du cheminement évolutif pour l'entreprise : s'organiser de manière à prendre en compte intégralement les exigences des différents secteurs d'activité. Les entreprises les plus efficaces en termes de prestation de services informatiques comparent leurs performances et celles de la concurrence. Selon l'étude menée par IDC, les créateurs de perspectives d'avenir sont jusqu'à trois fois plus susceptibles de suivre et d'évaluer sur une base concurrentielle les niveaux de services informatiques, en fonction d'indicateurs clés. Cela se traduit par davantage d'améliorations continues, puis de meilleurs partenariats avec des secteurs d'activité divers.",
    'itservicedelivery2'=>"Recommandation principale : pour mieux tirer parti de vos opérations et accroître votre efficacité, vous devez impérativement développer vos prestations de services informatiques. Grâce à des outils de gestion et des services autonomes, ainsi qu'un catalogue de prestations clairement définies, les services peuvent être appliqués de façon plus coordonnée et intégrée, d'où une prévisibilité et une convivialité accrues. L'automatisation des tâches libèrent du temps pour les développeurs et les administrateurs, qui peuvent ainsi se concentrer sur les innovations à valeur ajoutée. La satisfaction des utilisateurs et le suivi des performances applicatives peuvent apporter des informations précieuses pour comprendre vos points sensibles et vous épargner de coûteux temps d'arrêt.",
    'itservicedelivery3'=>"Recommandation principale : dans la mesure du possible, envisagez la mise en œuvre d'une infrastructure informatique partagée afin d'éviter tout chevauchement inutile et toute inefficacité au niveau de l'utilisation des ressources. L'espace au sol du datacenter ainsi que le fonctionnement et l'entretien du matériel est coûteux, notamment en termes de consommation d'énergie. Il est recommandé de faire tout le nécessaire pour consolider votre infrastructure de manière intégrée et partagée, avant de préserver votre compétitivité. Envisagez d'utiliser une solution d'infrastructure convergente, préintégrée et prête à l'emploi, de façon à accélérer votre transformation.",
    'itservicedelivery4'=>"Recommandation principale : les services informatiques et les outils de gestion complets ne doivent plus être considérés comme simplement agréables, mais comme essentiels pour maintenir vos systèmes en état de marche et éviter les temps d'arrêt et problèmes de sécurité coûteux. Ces outils favorisent également une gestion proactive de la qualité des services, la satisfaction continue des clients et des employés, ainsi que la réduction des coûts d'assistance. Ils peuvent également servir à des fins d'analyse pour obtenir un avantage concurrentiel, grâce à une meilleure compréhension des besoins de vos utilisateurs. Vérifiez si votre fournisseur d'infrastructures propose une solution de gestion de services intégrée dans le cadre de son offre. Cela vous évitera d'avoir à intégrer et à adapter des logiciels tiers coûteux.",
    'itservicedelivery5'=>"Recommandation principale : vos outils de gestion sont très élémentaires et fragmentés, et ne sont pas prêts à gérer des environnements de serveurs, stockage et réseau d'avenir toujours plus convergents. Envisagez une suite de gestion complète vous permettant de contrôler et comprendre votre infrastructure de manière globale. Vous pourrez ainsi optimiser votre utilisation des ressources et des processus opérationnels.",
    'itservicedelivery6'=>"Recommandation principale : la gestion informatique doit être automatisée afin d'accroître l'efficacité, la flexibilité et la cohérence. Il s'agit aussi de limiter les risques d'erreurs humaines, et de libérer du temps pour les développeurs et les administrateurs. Ceux-ci pourront ainsi se concentrer sur les activités à valeur ajoutée. À l'ère du numérique, vous devez généraliser l'automatisation pour rester compétitif et intégrer suffisamment toutes sortes de processus et de systèmes. Gardez bien cela à l'esprit lorsque vous vous lancez dans une entreprise d'automatisation afin d'identifier les économies potentielles à l'avance, de façon à les y réinvestir pour améliorer votre prestation de services.",
    'itservicedelivery7'=>"Recommandation principale : il ne suffit plus d'effectuer vos opérations informatiques de serveurs, stockage et réseau de manière cloisonnée, via des équipes dédiées. Ces trois domaines doivent être entièrement intégrés pour obtenir un avantage concurrentiel et éviter les goulots d'étranglement des processus internes. Il s'agit d'une tâche particulièrement difficile pouvant entraîner une redistribution des responsabilités du personnel, mais ce remaniement ne peut être évité si vous voulez vous préparer pour l'avenir.",
    'itinfrastructuresummary'=>"Selon vos réponses à cette catégorie, l'approche de votre entreprise en termes de technologie d'infrastructure informatique est",
    'itinfrastructure1'=>"Recommandation principale : une infrastructure convergente. Grâce à l'intégration des composants matériels et logiciels en un seul ensemble optimisé, les entreprises peuvent utiliser plus efficacement leurs ressources informatiques existantes. Elle fournit une base agile et évolutive sur laquelle les entreprises peuvent modifier leurs processus opérationnels et mettre en œuvre de nouveaux services. La vitesse et l'agilité sont des critères très importants, et l'automatisation des ressources informatiques, de stockage et de réseau en un seul volet de gestion est essentielle pour améliorer la disponibilité et réduire les coûts en utilisant plus activement les actifs au sein de toutes les ressources du datacenter. 
Comment les créateurs de perspectives d'avenir génèrent-ils encore plus de valeur de leur infrastructure informatique convergente ? En premier lieu, il convient de mesurer exactement les taux d'utilisation des ressources de traitement informatique, de stockage et de réseau. Ces nouveaux entrepreneurs utilisent des outils plus sophistiqués et mesurent l'utilisation de l'infrastructure plus régulièrement que les autres organisations. En outre, ils procèdent aux changements organisationnels requis pour obtenir le maximum d'avantages de leur infrastructure convergente. Ils s'efforcent de différencier leur entreprise de par leur utilisation d'applications, de données et d'infrastructure, et accordent plus de responsabilité à leurs équipes de développement pour ce qui concerne la gestion de l'automatisation et de la",
    'itinfrastructure2'=>"Recommandation principale : les solutions de cloud computing et de virtualisation d'infrastructure peuvent aider dans une certaine mesure les entreprises qui ont du mal à optimiser la valeur et la performance de leur matériel hérité. Toutefois, dans une perspective d'augmentation réelle de la compétitivité, vous devrez passer la vitesse supérieure en exploitant des ensembles intégrés de composants matériels et logiciels. L'infrastructure convergente peut regrouper des composants dans un seul package optimisé, ce qui vous permet d'accélérer la rentabilité et de mieux utiliser vos ressources informatiques existantes. Elle offre une base agile et évolutive sur laquelle vous pouvez compter dans le contexte de changement des processus métiers et de déploiement de nouveaux services.",
    'itinfrastructure3'=>"Recommandation principale : les services gérés et les solutions hébergées de tiers peuvent vous prêter main forte en mettant à votre disposition des environnements pré-construits ou basés sur les meilleures pratiques, ce qui vous permet de vous concentrer sur votre cœur de métier. En effet, votre structure informatique est alors prise en charge par des sociétés sélectionnées, spécialisées dans ce domaine. Bien que l'externalisation de votre informatique ne soit pas toujours l'option la plus judicieuse, il est généralement recommandé d'évaluer les différentes offres sur le marché et de les utiliser pour éviter de vous faire surclasser en termes de compétitivité, d'efficacité et d'évolutivité. Il est essentiel d'intégrer étroitement ces services dans votre environnement sur site et de gérer ces relations fournisseurs en appliquant une vision claire basée sur l'unification des aspects techniques et commerciaux.",
    'itinfrastructure4'=>"Recommandation principale : les services de cloud public peuvent mettre en œuvre une utilisation plus agile, performante et efficace de l'infrastructure et des ressources informatiques, aux fins d'augmenter votre capacité de service sans rien changer à votre budget. Le cloud public peut renforcer l'agilité de l'entreprise, et vous permettre de répondre plus rapidement aux défis de la concurrence, dans le but d'évoluer dans votre secteur en position de leader en stratégie de transformation. De nouveaux produits et services peuvent être testés et déployés plus rapidement et avec un minimum de risque, en activant une mise à l'échelle instantanée des ressources cloud en cas de besoin. Les entreprises les plus dynamiques ont mis en place des stratégies hybrides permettant le mouvement transparent des charges de travail au sein des ressources sur site et celles du cloud public.",
    'itinfrastructure5'=>"Recommandation principale : afin d'obtenir un avantage compétitif dans cette économie de plus en plus numérique, vous devez chercher à renforcer vos qualités de novateur et expérimenter de nouvelles technologies avant vos concurrents. N'attendez pas que tous vos homologues aient approuvé un nouveau matériel ou logiciel, mais recherchez activement des approches novatrices pertinentes pour votre entreprise. Cette réactivité nécessite souvent l'intégration de serveurs et de logiciels de stockage, de réseau et de gestion en tant que systèmes convergents. Demandez des conseils à votre intégrateur système local qui pourra vous expliquer les différentes approches et évaluer les économies potentielles ainsi que les gains de flexibilité et les atouts en termes d'innovation que vous pourriez concrétiser en procédant à une nouvelle mise en œuvre. Il convient aussi d'aligner vos équipes opérationnelles internes et votre approche de gestion du changement, de sorte à pouvoir tirer le meilleur parti de l'adoption de nouvelles technologies.",
    'itinfrastructure6'=>"Recommandation principale : il vous faut disposer d'un plan clair pour cadrer l'achat de votre infrastructure de serveur, de stockage et de réseau. Ne vous contentez pas de regrouper les exigences de vos équipes. Le processus d'achat de vos machines doit répondre à une stratégie planifiée, vouée à créer une solution globale évitant la fragmentation, ainsi que tout dysfonctionnement au niveau des activités de gestion et de support. Pour autant, vous devez éviter la dépendance envers un seul fournisseur. Toutefois, la plupart des entreprises estiment que les systèmes convergents offrent un avantage concurrentiel et une rentabilisation plus rapide si les éléments d'infrastructure sont séparés, moins intégrés et faciles à gérer.",
    'conclusion'=>'CONCLUSION',
    'conclusionsummary'=>"
L'informatique évolutive est un vecteur clé pour les entreprises d'aujourd'hui, et les organisations affichant les plus hauts niveaux d'évolutivité s'adaptent rapidement aux perturbations, et dynamisent également leur processus d'innovation. Les initiatives mises en place pour atteindre des niveaux plus élevés d'évolutivité ne sont pas sans risque, et il convient d'éviter certains pièges, notamment :
<ul style=\"color: #2A96DE; line-height: 1.5; list-style-type:img|png|2|2|'.K_PATH_IMAGES.'/bullet.png\">
    <li>Absence de plan. Les entreprises doivent adopter une stratégie réfléchie quant à leur approche d'évolutivité. Cette phase de préparation ne se borne pas à ajouter aveuglément de nouvelles technologies à la structure informatique. Elle impose la mise en place de l'organisation, des compétences et des pratiques nécessaires pour tirer parti de cette technologie. En outre, celle-ci doit étayer des initiatives commerciales cruciales.</li>
    <li>Dépendance envers un système propriétaire. La clé de l'évolutivité réside dans la souplesse, à savoir la capacité de s'adapter aux circonstances imprévues. La dépendance envers un système ou cadre unique limite la flexibilité de l'entreprise et augmente le risque de se retrouver dans une impasse technologique.</li>
    <li>Prise de risques. Les entreprises doivent adopter une approche graduelle pour optimiser leur évolutivité, en étoffant progressivement l'infrastructure et les pratiques informatiques en place. Les enjeux clés de l'entreprise dépendent dans une large mesure de l'informatique. Aussi, le processus d'amélioration de l'infrastructure est comparable à une greffe du cœur. Une implémentation de changements rapides et massifs, même si cela correspond à une approche assurant une grande rapidité d'opération afin de prendre l'ascendant sur la concurrence, introduit aussi des risques qui pourraient nuire à l'entreprise.</li>
</ul>
Heureusement, des efforts d'optimisation limités suffisent aux entreprises les moins évolutives pour commencer à constater des améliorations de leurs structures. L'évolutivité est un processus progressif où chaque étape d'évolution génère déjà une amélioration structurelle sensible. Les entreprises peuvent aussi choisir de mettre l'accent sur le domaine technique ou pratique le plus approprié selon leurs besoins, et continuer quand même à constater des améliorations. Toutefois, deux éléments sont essentiels pour la réussite à tous les niveaux : une approche stratégique pour piloter les décisions structurelles au lieu d'une stratégie à court terme axée sur la réduction des coûts, d'une part, et un service informatique capable de travailler en étroite collaboration avec les secteurs d'activité pour répondre aux besoins de l'entreprise, d'autre part.",
    'sponsored'=>'Sponsored by DELL'
);