<?php

return array(
    'results'=>'ERGEBNISSE',
    'thankyou'=>"Vielen Dank, dass Sie an der von Dell und Intel gesponserten IDC-Bewertung „Ist Ihre Infrastruktur zukunftsfähig?“ teilnehmen. Die wirtschaftlichen Vorteile einer zukunftsreifen Infrastruktur liegen klar auf der Hand: eine bessere Zukunftsfähigkeit entspricht besseren geschäftlichen Ergebnissen. 

Unternehmen müssen nicht an der Spitze der Zukunftsfähigkeitsskala liegen, um sich Vorteile zunutze zu machen; die Ergebnisse einer Reihe von bei IDC zusammengelaufenen IT- und Cloud-Umfragen haben gezeigt, dass Unternehmen sich bereits dann Vorteile sichern, wenn sie den nächsten Schritt in Richtung Zukunftsfähigkeit gehen, ganz unabhängig vom Ausgangspunkt. Unternehmen, die ihre „Zukunftsfähigkeit“ konsequent verbessern, verkürzen damit die Markteinführungszeit neuer Produkte und Dienstleistungen, steigern die Agilität des Unternehmens und die Produktivität der Mitarbeiter und sorgen sogar für eine bessere Innovationsfähigkeit. 

Je zukunftsreifer ein IT-Unternehmen ist, desto mehr kann es sich über erhebliche geschäftliche Vorteile der Konkurrenz gegenüber freuen. Dazu gehören folgende:",
    'aims'=>'Diese Umfrage wurde mit dem Ziel entwickelt, festzustellen inwieweit Ihr Unternehmen heute und in Zukunft in der Lage ist, mit den steigenden Anforderungen umzugehen, die Unternehmen an die IT-Infrastruktur stellen. Wir haben uns folgende Schlüsselbereiche angesehen:',
    'bullets'=>'
<ul style="color: #2A96DE; line-height: 1.5; list-style-type:img|png|2|2|'.K_PATH_IMAGES.'/bullet.png">
    <li>Kürzere Markteinführungszeit für neue Produkte und Dienstleistungen, wodurch Vorteile gegenüber Konkurrenten besser genutzt werden können</li>
    <li>Überlegene Agilität und Flexibilität, die es dem Unternehmen ermöglichen, Änderungen im Markt vorherzusehen und rasch auf diese zu reagieren, drohende Risiken abzumildern und Chancen zu nutzen</li>
    <li>Gesteigerte Produktivität der Mitarbeiter, die es dem Unternehmen ermöglicht, geschäftliche Prozesse zu optimieren und die Kosten zu senken um auf diese Weise bessere Ergebnisse zu erzielen</li>
    <li>Größere Kundenzufriedenheit durch Bereitstellung von zuverlässigeren, intuitiveren und besser funktionierenden Dienstleistungen für Mitarbeiter, Partner und Kunden</li>
    <li>Innovation, die es dem Unternehmen ermöglicht, mit seinen Ressourcen und geschäftlichen Aktivitäten neue Geschäftsfelder zu erschließen</li>
    <li>Effizientere IT-Abläufe, die zur Kostensenkung beitragen und gleichzeitig eine skalierbarere Infrastruktur schaffen</li>
    <li>Aktivierung mobiler Funktionen zur Bereitstellung einer umfassenden Palette von Geschäftsanwendungen</li>
<ul>',
    'looked'=>'Wir haben uns folgende Schlüsselbereiche angesehen:',
    'itbusiness'=>'IT und Unternehmen',
    'itservicedelivery'=>'IT-Service-Bereitstellung',
    'itinfrastructure'=>'IT-Infrastrukturtechnologie',

    'based'=>'Auf der Grundlage Ihrer Antworten stufen wir die Zukunftsfähigkeit Ihrer IT-Infrastruktur insgesamt wie folgt ein:',
    'currentintro'=>'Evolutionärer Ansatz in Bezug auf die IT-Infrastruktur und eine IT-Transformation die von Einzelpersonen ausgeht. IT und das Unternehmen funktionieren auf der Grundlage von Anfragen/Anforderungen.',
    'future-awareintro'=>'Evolutionärer Ansatz in Bezug auf IT-Servicebereitstellung und eine am Team orientiere IT-Transformation. Die IT ist in bestimmten Unternehmensbereichen auf das Unternehmen abgestimmt.',
    'future-focusedintro'=>'Revolutionärer Ansatz in Bezug auf IT-Servicebereitstellung und eine unternehmensorientiere IT-Transformation. IT und das Unternehmen sind auf eine Reihe wichtiger Aktivitäten abgestimmt.',
    'future-creatorintro'=>'Revolutionärer Ansatz in Bezug auf das digitale Unternehmen mit geschäftsorientierter IT-Transformation. IT/Geschäftszweige sind in Bezug auf alle wichtigen Aktivitäten aufeinander abgestimmt.',

    'currentaware'=>'Sie wurden als #STATUS# eingestuft und haben noch einiges zu tun, um die Zukunftsfähigkeit Ihrer IT-Infrastruktur zu verbessern. Aber lassen Sie sich nicht entmutigen. Zukunftsfähigkeit ist ein fortlaufender Prozess, und Sie können durch die Verbesserung Ihrer Zukunftsfähigkeit unabhängig von Ihrem Ausgangspunkt eine erhebliche Verbesserung Ihrer geschäftlichen Ergebnisse erreichen. Sie können bessere geschäftliche Ergebnisse erzielen, indem Sie sich auf die Optimierung bestimmter Aspekte der IT-Zukunftsfähigkeit konzentrieren, die wir für Sie herausgearbeitet haben:',
    'focusedcreator'=>'Sie wurden als #STATUS# eingestuft und sind auf einem recht guten Weg, was die Zukunftsfähigkeit Ihrer IT-Infrastruktur betrifft. Aber auch für diejenigen, die gut aufgestellt sind, ist Zukunftsfähigkeit ein fortlaufender Prozess, wobei Sie immer noch Optimierungen Ihrer geschäftlichen Ergebnisse erzielen können, indem Sie Ihre Zukunftsfähigkeit verbessern. In dem Maß, wie sich Technologien, Geschäftspraktiken und die Nachfrage des Marktes im Laufe der Zeit ändern, muss sich auch das Zukunftsfähigkeitskonzept entwickeln. Wenn sie ihre Zukunftsfähigkeit erhalten wollen, dürfen Unternehmen nicht selbstzufrieden werden. Denken Sie daran, dass die Zukunftsfähigkeit ein fortlaufender Prozess ist, und bleiben Sie so beweglich, flexibel und innovativ, dass Sie Ihren Wettbewerbsvorteil gegenüber der Konkurrenz aufrechterhalten. Sie können bessere geschäftliche Ergebnisse erzielen, indem Sie sich auf die Optimierung bestimmter Aspekte der IT-Zukunftsfähigkeit konzentrieren, die wir für Sie herausgearbeitet haben:',

    'basedimprove'=>'Based on your responses you can look to improve your overall score by focusing on improving your:',
    'overall'=>'Insgesamt Bereitschaft',
    'yourscore'=>'IHRE PUNKTZAHL',
    'baselinescore'=>'GRUNDWERT',
    'section'=>'WERTE ERREICHT HAT',
    'getahead'=>'Welche Verbesserungsmaßnahmen wären sinnvoll?',
    'itbusinesssummary'=>'Auf der Grundlage Ihrer Antworten in diesem Abschnitt wird das Verhältnis Ihres Unternehmens zwischen IT und Geschäftstätigkeit als',
    'itbusiness1'=>"Wichtigste Empfehlung: Eine gute IT beginnt mit einer guten Geschäftsstrategie und der richtigen Vorgehensweise. In der heutigen digitalen Welt sollte man die IT nicht mehr als reinen Kostenfaktor betrachten, sondern als entscheidenden Bestandteil der Wettbewerbsstrategie. Die IT muss in der Lage sein, geschäftliche Anforderungen in Technologie und Services umzusetzen. Es reicht nicht aus, die modernsten Geräte zu kaufen, sondern die Systeme müssen ausreichend integriert sein, und die geschäftlichen Prozesse und Strukturen müssen entsprechend abgestimmt werden. Unternehmen, die innovative Ansätze auf ihre Infrastruktur anwenden und unternehmensorientiert umsetzen, bleiben meist an der Spitze des Feldes und können sich auf die Schaffung von Mehrwert konzentrieren, anstatt wertvolle Zeit, Geld und Energie für Korrekturmaßnahmen aufzuwenden.",
    'itbusiness2'=>"Wichtigste Empfehlung: IT-Organisationen mit der besten Zukunftsfähigkeit sind in der Tat eine Hilfe für ihre Unternehmen, wenn es um die Anpassung an wechselnde Marktbedingungen geht, und ermöglichen Ihnen, neue Einnahmequellen zu nutzen, wann immer sich diese ergeben. Die Verbesserung der Beziehungen zu Geschäftsführern kann zu einem besseren Verständnis des Mehrwertes einer zukunftsfähigen IT-Organisationund Verbesserungen beitragen. Diese müssen umgesetzt werden, um mit der Konkurrenz Schritt halten zu können. Ihre Stellung im Unternehmen könnte an Bedeutung gewinnen, wenn es Ihnen gelingt, die IT als Umsatzträger einzusetzen. Wenn Sie allerdings keine Fortschritte erzielen, könnte Ihre Rolle eher administrativ werden, wobei aufgrund steigender Nachfrage von Endnutzern und des Wachstums der Schatten-IT der Druck auf Sie zunehmen könnte.",
    'itbusiness3'=>"Wichtigste Empfehlung: Investitionen sind bei der Entwicklung einer funktionsfähigen und agilen IT-Organisation von entscheidender Bedeutung. Sie kämpfen derzeit um die Finanzierung laufender IT-Projekte oder entwickeln neue Initiativen mit dem Ergebnis, dass Sie sich bei der Transformation der IT mit Herausforderungen konfrontiert sehen. Sie sollten in Bezug auf Ihre IT-Strategie einen neuen Ansatz in Betracht ziehen, der den Mehrwert in den Mittelpunkt stellt, welcher durch die IT-Transformation für das Unternehmen erzielt werden kann. Hierdurch lassen sich die Einsparungen ermitteln, die sich durch eine Verbesserung der Effizienz erzielen und anschließend in den Aufbau einer modernen Plattform investieren lassen, um dem Unternehmen neue Dienstleistungen anbieten zu können.",
    'itbusiness4'=>"Wichtigste Empfehlung: Sie haben mit Änderungen zu kämpfen, was nichts anderes bedeutet, als dass Ihr Unternehmen Schwierigkeiten hat, auf wechselnde Marktbedingungen zu reagieren. Konzentrieren Sie sich darauf, Veränderungen vorhersehbar zu machen, um schneller darauf reagieren zu können, indem Sie Lücken und Schwachstellen in Ihren Tools und Prozessen unter die Lupe nehmen. Ihre Systeme und Betriebsabläufe müssen analysiert und möglicherweise auf den neuesten Stand gebracht werden, um zu gewährleisten, dass sie den wichtigsten geschäftlichen Zielvorgaben entsprechen und auf das digitale Zeitalter vorbereitet sind. Ihre Abteilung muss möglicherweise auch ihr Leistungsportfolio erweitern, indem entsprechende Fachkräfte eingestellt oder ausreichende Weiterbildungsmöglichkeiten angeboten werden. Eine effiziente Zusammenarbeit innerhalb Ihres Teams und mit den geschäftlichen Entscheidungsträgern ist für den Umgang mit den Herausforderungen bezüglich der Unternehmens- und IT-Transformation von entscheidender Bedeutung.",
    'itbusiness5'=>"Wichtigste Empfehlung: Wenn viele Projekte ohne das erforderliche Maß an Mitarbeit durch die IT-Abteilung durchgeführt werden, ist die IT im Unternehmen nicht richtig integriert. Ihr Hauptaugenmerk sollte auf dem Aufbau und der Verbesserung der Beziehungen zwischen der IT-Abteilung und dem Unternehmensmanagement bzw. der für das jeweilige Geschäftsfeld zuständigen Geschäftsleitung liegen, wobei Sie gleichzeitig sicherstellen sollten, dass sich die Geschäftsführung der Fähigkeiten und Erfolge der IT-Abteilung bewusst ist. Dies erfordert neue Denkansätze von beiden Seiten, um dafür zu sorgen, dass die IT-Abteilung als interner Dienstleister betrachtet wird, der entscheidend zum Unternehmenswert beiträgt, und nicht als notwendiges Übel im Back-Office.",
    'itbusiness6'=>"Wichtigste Empfehlung: Selbstbewusstsein und Ermittlung von Lücken und Schwachstellen sind von entscheidender Bedeutung, wenn man feststellen möchte, worauf man sich bei der Verbesserung der IT konzentrieren muss. Sie sollten zumindest anstreben, eine formelle Überprüfung der Leistung und Fähigkeiten der IT-Abteilung durchzuführen. Im Idealfall sollten Sie erfahrene Fachleute hinzuziehen, die unvoreingenommen beurteilen können, welche Maßnahmen auf der Grundlage branchenweit bewährter Praktiken erforderlich sind. Wenn Sie sich die geschäftlichen Erfolge und Änderungen der jeweiligen IT-Strategie Ihrer Konkurrenten betrachten, könnte Ihnen dies helfen, die Korrelation zwischen diesen Faktoren besser zu verstehen, um einen Schritt weiter zu kommen und Ihre Stärken und Schwächen richtig einzuschätzen.",
    'itservicedeliverysummary'=>"Auf der Grundlage Ihrer Antworten in diesem Abschnitt wird die Fähigkeit Ihres Unternehmens in Bezug auf IT-Servicebereitstellung als",
    'itservicedelivery1'=>"Wichtigste Empfehlung: Effektiv arbeitende und in das Unternehmen eingebundene IT-Abteilungen sind die Grundlage eines jeden modernen digitalen Unternehmens. Eine effektive IT-Abteilung verfügt über die richtigen Mitarbeiter mit den richtigen Fähigkeiten, um die Vorzüge dieser Technologien umzusetzen und zu maximieren. Um in Bezug auf Zukunftsfähigkeit voranzukommen, muss die IT-Abteilung mit jedem Geschäftszweig zunehmend strategisch zusammenarbeiten. Die Herstellung der vollständigen Reaktionsfähigkeit im Hinblick auf die Anforderungen des jeweiligen Geschäftsfelds ist der entscheidende erste Schritt auf dem Weg zu einem zukunftsfähigen Unternehmen. Die Organisationen mit der besten IT-Servicebereitstellung vergleichen ihre Serviceleistung mit der anderer Unternehmen. Untersuchungen von IDC zeigen, dass zukunftsgestaltende Unternehmen eine dreifach höhere Wahrscheinlichkeit aufweisen, IT-Servicelevels auf hohem Niveau zu erreichen, und damit für die Konkurrenz Maßstäbe setzen. Dies führt zu kontinuierlicheren Verbesserungen und letztendlich zu besseren Partnerschaften mit verschiedenen Geschäftszweigen.",
    'itservicedelivery2'=>"Wichtigste Empfehlung: Die Fähigkeit Ihres Unternehmens in Bezug auf IT-Servicebereitstellung ist entscheidend, um aus Ihren geschäftlichen Aktivitäten einen größeren Nutzen zu ziehen und die Effizienz zu erhöhen. Indem Sie Self-Service-Bereitstellungsfunktionen und Management-Tools sowie einen klar definierten Servicekatalog zur Verfügung stellen, können Sie Ihre Dienstleistungen besser koordinieren und integrieren und damit die Vorhersehbarkeit und Benutzerfreundlichkeit erhöhen. Die Automatisierung von Aufgaben verschafft Entwicklern und Administratoren mehr Zeit, um sich auf wertsteigernde Innovationen zu konzentrieren. Die Überwachung der Benutzerzufriedenheit und der Anwendungsleistung kann wertvolle Erkenntnisse in Bezug auf Ihre Schwachstellen liefern und dazu beitragen, kostspielige Ausfallzeiten zu verhindern.",
    'itservicedelivery3'=>"Wichtigste Empfehlung: Ziehen Sie die Bereitstellung einer gemeinsamen IT-Infrastruktur in Erwägung, wann immer dies möglich ist, um unnötige Überlappungen und mangelnde Effizienz bei der Ressourcennutzung zu vermeiden. Die Raumnutzung für Rechenzentren sowie der Betrieb und die Wartung von Hardware ist kostspielig, insbesondere der Stromverbrauch. Wir empfehlen Ihnen, sich nach Kräften zu bemühen, Ihre Infrastruktur zu konsolidieren, gemeinsam zu nutzen und in Unternehmensabläufe zu integrieren, um wettbewerbsfähig zu bleiben. Ziehen Sie eine konvergente Infrastrukturlösung in Betracht, die bereits auf eine Integration vorbereitet und sofort einsatzfähig ist, um die Umstellung zu beschleunigen.",
    'itservicedelivery4'=>"Wichtigste Empfehlung: Investitionen in End-to-End IT-Service-Überwachungs- und Management-Tools sollten nicht länger als zusätzliche Anschaffungen am Rande betrachtet werden, sondern als essentielle Werkzeuge, um Ihre Systeme am Laufen zu halten und kostspielige Ausfallzeiten oder Sicherheitsprobleme zu vermeiden. Diese Tools tragen auch zu einem proaktiven Servicequalitätsmanagement bei, halten Ihre Kunden und Mitarbeiter bei Laune und senken die Support-Kosten. Zudem stellen sie nützliche Analysefunktionen bereit, die Ihnen helfen, einen Vorsprung gegenüber der Konkurrenz zu erreichen, indem Sie die Bedürfnisse Ihrer Kunden besser verstehen. Finden Sie heraus, ob Ihr Infrastrukturanbieter eine ausreichend unterstützte und integrierte Servicemanagementlösung im Angebot hat, um die Einbindung und Anpassung teurer Software von Drittanbietern zu vermeiden.",
    'itservicedelivery5'=>"Wichtigste Empfehlung: Ihre Management-Tools haben nur Einsteigerniveau, stellen keine einheitliche Lösung dar und sind auf das Management der zunehmend konvergenten Server-, Speicher- und Netzwerkumgebungen der Zukunft nicht vorbereitet. Ziehen Sie die Implementierung einer End-to-End-Managementlösung in Betracht, die Ihnen eine ganzheitliche Kontrolle und Überwachung Ihrer Infrastruktur ermöglicht, sodass Sie Ihre Ressourcennutzung und operativen Prozesse optimieren können.",
    'itservicedelivery6'=>"Wichtigste Empfehlung: Das Management Ihrer IT muss automatisiert werden, um Effizienz, Agilität und Konsistenz zu erhöhen, das Risiko menschlicher Fehler zu minimieren und Administratoren und Entwicklern mehr Zeit zu verschaffen, um sich auf wertsteigernde Aktivitäten zu konzentrieren. Im digitalen Zeitalter ist der Einsatz automatisierter Abläufe generell Pflicht, um wettbewerbsfähig zu bleiben und in der Lage zu sein, verschiedene Prozesse und Systeme ausreichend zu integrieren. Denken Sie bei Ihren Automatisierungsbemühungen daran, vorab potenzielle Einsparungen zu ermitteln, um diese für Neuinvestitionen in die IT und damit für die Servicebereitstellung zu sichern.",
    'itservicedelivery7'=>"Wichtigste Empfehlung: Es reicht nicht mehr aus, dass Ihre IT-Abläufe in separaten Teams für Server, Speicher und Netzwerk erfolgen, die als Silos fungieren. Alle drei Bereiche müssen vollständig integriert werden, um einen Wettbewerbsvorteil zu erzielen und interne Prozessengpässe zu vermeiden. Dies ist eine recht anspruchsvolle Aufgabe und kann dazu führen, dass Zuständigkeiten von Mitarbeitern neu organisiert werden müssen, ist aber letztlich nicht zu umgehen, wenn Sie auf die Zukunft vorbereitet sein möchten.",
    'itinfrastructuresummary'=>"Auf der Grundlage Ihrer Antworten in diesem Abschnitt wird der Ansatz Ihres Unternehmens in Bezug auf IT-Infrastrukturtechnologie als",
    'itinfrastructure1'=>"Wichtigste Empfehlung: Konvergente Infrastruktur bedeutet, integrierte Hardware- und Software-Komponenten zu nutzen, die in einem einzigen optimierten Paket kombiniert sind, um dem Unternehmen zu ermöglichen, seine vorhandenen IT-Werte besser einzusetzen. Sie sorgt für eine agile, skalierbare Grundlage, auf die sich das Unternehmen verlassen kann, wenn es seine Geschäftsabläufe ändert und neue Dienstleistungen anbietet. Geschwindigkeit und Agilität sind sehr wichtig, wobei die Automatisierung der Verwaltung von Rechen-, Netzwerk- und Speicherressourcen mit einer einzigen Managementplattform entscheidend ist, um die Verfügbarkeit zu verbessern und die Kosten durch verbesserte Nutzung der jeweiligen Rechenzentrumsressourcen zu senken.

Wie schaffen zukunftsgestaltende Unternehmen einen Mehrwert durch eine konvergente IT-Infrastruktur? Es fängt mit der genauen Messung der Nutzungsraten der Rechen-, Netzwerk- und Speicherressourcen an. Diese Unternehmen machen sich anspruchsvollere Tools zunutze und messen die Infrastrukturnutzung regelmäßiger im Vergleich zu anderen Unternehmen. Sie setzen auch die organisatorischen Änderungen um, die notwendig sind, um aus ihrer konvergenten Infrastruktur den größten Nutzen zu ziehen. Sie achten aktiv darauf, ihr Unternehmen von anderen abzuheben, indem sie Anwendungen, Daten und Infrastruktur einsetzen und ihren Entwicklungsteams gleichzeitig mehr Verantwortung für die IT-Automatisierung und das Konfigurationsmanagement übertragen.",
    'itinfrastructure2'=>"Wichtigste Empfehlung: Die Virtualisierung der Infrastruktur und Cloud-Lösungen können bei Unternehmen für eine gewisse Entlastung sorgen, deren Ziel es ist, ihre alte Hardware besser zu nutzen und deren Leistung zu steigern. Wenn Sie allerdings wirklich wettbewerbsfähig sein möchten, müssen Sie einen Schritt weiter gehen, indem Sie integrierte Hardware- und Software-Komponenten zu Ihrem Vorteil nutzen. Konvergente Infrastrukturen können verschiedene Komponenten in einem einzigen optimierten Paket zusammenfassen und es Ihnen auf diese Weise ermöglichen, eine schnellere Amortisierung zu erzielen und Ihre vorhandenen IT-Ressourcen besser einzusetzen. Sie sorgen für eine agile, skalierbare Grundlage, auf die Sie sich verlassen können, wenn sich Ihre Geschäftsabläufe ändern und Sie neue Services einführen.",
    'itinfrastructure3'=>"Wichtigste Empfehlung: Von externen Anbietern verwaltete Services und gehostete Lösungen können für Sie nützlich sein, weil sie bewährte Praktiken bzw. vorbereitete Umgebungen anbieten, die es Ihnen ermöglichen, sich auf Ihr Kerngeschäft zu konzentrieren, während sich ausgewählte Anbieter, die auf dieses Gebiet spezialisiert sind, um Ihre IT kümmern. Auch wenn das Outsourcing Ihrer IT nicht immer die beste Lösung darstellt, ist es allgemein empfehlenswert, die verschiedenen Angebote auf dem Markt zu bewerten und bei Bedarf zu nutzen, um in puncto Wettbewerbsfähigkeit, Effizienz und Skalierbarkeit nicht zurückzufallen. Es ist von entscheidender Bedeutung, diese Services eng in Ihr geschäftliches Umfeld vor Ort zu integrieren und die Beziehungen mit Drittanbietern mit der klaren Zielsetzung zu pflegen, geschäftliche und technische Aspekte zu vereinen.",
    'itinfrastructure4'=>"Wichtigste Empfehlung: Öffentliche Cloud-Services können zu einer flexibleren und effektiveren Nutzung der IT-Infrastruktur und -Ressourcen führen, die bei einem gleichbleibenden IT-Budget eine bessere Bereitstellung ermöglicht. Eine Public Cloud-Lösung kann die geschäftliche Agilität verbessern, was zu einer besseren Reaktionsfähigkeit gegenüber Wettbewerbern führen kann, die es Ihnen ermöglicht, bei der branchenweiten Transformation eine Führungsposition einzunehmen. Neue Produkte und Services können durch spontane Aufwärts- und Abwärtsskalierung von Cloud-Ressourcen nach Bedarf schneller getestet und mit geringerem Risiko auf den Markt gebracht werden. Die fortschrittlichsten Unternehmen verfügen über Hybridstrategien, die ihnen eine nahtlose Verschiebung der Workloads zwischen Ihren eigenen Ressources sowie der Public Cloud ermöglichen.",
    'itinfrastructure5'=>"Wichtigste Empfehlung: Um in unserem zunehmend digitalen Zeitalter einen Wettbewerbsvorteil zu erzielen, sollten Sie darauf achten, ein Innovator zu werden und versuchen, neue Technologien vor Ihren Wettbewerbern auszuprobieren. Warten Sie nicht, bis all Ihre Konkurrenten eine neue Hardware oder Software einsetzen, sondern halten Sie aktiv nach innovativen Ansätzen Ausschau, die für Ihr Unternehmen relevant sind. Diese erfordern häufig die Integration von Servern, Speicher, Netzwerk und Management-Software in Form eines konvergenten Systems. Lassen Sie sich von Ihrem Systemintegrator beraten, der Ihnen die unterschiedlichen Ansätze erläutern sowie die Kosteneinsparungen, Flexibilisierungsmöglichkeiten und innovativen Potenziale bewerten kann, die Sie durch eine Neuimplementierung erzielen können. Sorgen Sie für eine entsprechende Abstimmung mit Ihren internen operativen Teams und Ihrem Change Management, sodass Sie aus der Einführung neuer Technologien den größten Nutzen ziehen können.",
    'itinfrastructure6'=>"Wichtigste Empfehlung: Sie müssen einen klaren Plan zum Kauf Ihrer Server-, Speicher- und Netzwerkinfrastruktur entwickeln. Es reicht nicht aus, die verschiedenen Anforderungen Ihrer Teams einfach zusammenzuführen. Der Kauf Ihrer Systeme muss strategisch und ganzheitlich erfolgen, um Fragmentierung sowie Management- und Support-Probleme zu vermeiden. Dies bedeutet nicht, dass Sie sich verpflichtet fühlen müssen, nur bei einem Anbieter zu kaufen. Die meisten Unternehmen finden jedoch, dass konvergente Systeme gegenüber separaten, weniger integrierten und schlechter handhabbaren Infrastrukturelementen einen Wettbewerbsvorteil bieten und für eine schnellere Amortisierung sorgen.",
    'conclusion'=>'FAZIT',
    'conclusionsummary'=>'
Zukunftsfähige IT ist ein Schlüsselfaktor für heutige Unternehmen, wobei die Unternehmen mit der besten Zukunftsfähigkeit Störungen nicht nur schneller überwinden, sondern auch Innovationen fördern. Um ein bessere Zukunftsfähigkeit zu erreichen, muss man Risiken und Fallstricke vermeiden. Hierzu zählen:
<ul style="color: #2A96DE; line-height: 1.5; list-style-type:img|png|2|2|'.K_PATH_IMAGES.'/bullet.png">
    <li>Planloses Vorgehen - Unternehmen müssen in Bezug auf das Erreichen Ihrer Zukunftsfähigkeit überlegt und sorgfältig vorgehen. Zukunftsfähig zu werden erfordert mehr als nur die IT-Abteilung mit neuen Technologien auszustatten. Es müssen Fähigkeiten und Praktiken eingesetzt werden, die für die Nutzung dieser Technologien notwendig sind. Ferner muss die Technologie die entscheidenden geschäftlichen Initiativen unterstützen.</li>
    <li>Bindung an proprietäre Angebote - Der entscheidende Faktor in puncto Zukunftsfähigkeit ist die Flexibilität, sich auf unvorhergesehene Umstände einstellen zu können. Die Bindung an proprietäre Angebote oder Rahmenverträge schränken die Flexibilität des Unternehmens ein und erhöhen das Risiko, in eine technologische Sackgasse zu geraten.</li>
    <li>Hohe Einsätze - Unternehmen sollten bei der Verbesserung ihrer Zukunftsfähigkeit schrittweise vorgehen und nach und nach auf der IT-Infrastruktur und auf den Praktiken aufbauen, die bereits vorhanden sind. Da so vieles im Unternehmen von der IT abhängt, entspricht die Aktualisierung der IT-Infrastruktur einer organisatorischen Herztransplantation. Ein Austausch der kompletten IT, der die Möglichkeit verspricht, sich mit einem Schlag an die Spitze zu setzen, birgt auch Risiken, die das Unternehmen beeinträchtigen können.</li>
</ul>
Glücklicherweise müssen Unternehmen, die sich am unteren Ende der Zukunftsfähigkeitsskala befinden, nicht gleich die höchste Zukunftsfähigkeit erreichen, um Verbesserungen wahrzunehmen. Zukunftsfähigkeit ist eine Reise, und wenn Sie auch nur eine Stufe höher steigen, verbessern sich Ihre geschäftlichen Ergebnisse unabhängig von Ihrem Ausgangspunkt. Unternehmen werden auch dann schon Verbesserungen feststellen, wenn sie sich auf eine beliebige Technologie oder einen Praxisbereich konzentrieren, die bzw. der für ihre geschäftlichen Anforderungen am besten geeignet scheint. Allerdings sind zwei Faktoren über alle Stufen hinweg erfolgsentscheidend: erstens ein strategischer Ansatz, der hinter geschäftlichen Entscheidungen steht (anstelle einer kurzfristigen Konzentration auf Kosteneinsparungen), sowie zweitens eine IT-Organisation, die eng mit den Geschäftszweigen zusammenarbeiten kann, um den Anforderungen des Unternehmens Rechnung zu tragen.',
    'sponsored'=>'Sponsored by DELL'
);